model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: https://bio-sf-ai.openai.azure.com
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
      base_model: gpt-4o
      stream: false     # <---- THIS FIXES YOUR ERROR

general_settings:
  master_key: sk-1234

litellm_settings:
  drop_params: true
  set_verbose: true